In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('adult.csv')
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [6]:
# all the columns are filled
# import logical regression package
from sklearn.linear_model import LogisticRegression

In [7]:
# choose random parameters/columns + key parameter = income
# except education -> choose educational-num (already with unified number values)
selectedColumns = data[ [ 'age', 'educational-num', 'occupation', 'gender', 'native-country', 'income' ] ]

# 
X = pd.get_dummies( selectedColumns, columns = [ 'gender', 'native-country', 'occupation' ] )

# income => key column --> need to remove
del X['income']
X.head()

age  educational-num  gender_Female  gender_Male  native-country_?  \
0   25                7          False         True             False   
1   38                9          False         True             False   
2   28               12          False         True             False   
3   44               10          False         True             False   
4   18               10           True        False             False   

   native-country_Cambodia  native-country_Canada  native-country_China  \
0                    False                  False                 False   
1                    False                  False                 False   
2                    False                  False                 False   
3                    False                  False                 False   
4                    False                  False                 False   

   native-country_Columbia  native-country_Cuba  ...  \
0                    False                False  ...   
1                    False                False  ...   
2                    False                False  ...   
3                    False                False  ...   
4                    False                False  ...   

   occupation_Farming-fishing  occupation_Handlers-cleaners  \
0                       False                         False   
1                        True                         False   
2                       False                         False   
3                       False                         False   
4                       False                         False   

   occupation_Machine-op-inspct  occupation_Other-service  \
0                          True                     False   
1                         False                     False   
2                         False                     False   
3                          True                     False   
4                         False                     False   

   occupation_Priv-house-serv  occupation_Prof-specialty  \
0                       False                      False   
1                       False                      False   
2                       False                      False   
3                       False                      False   
4                       False                      False   

   occupation_Protective-serv  occupation_Sales  occupation_Tech-support  \
0                       False             False                    False   
1                       False             False                    False   
2                        True             False                    False   
3                       False             False                    False   
4                       False             False                    False   

   occupation_Transport-moving  
0                        False  
1                        False  
2                        False  
3                        False  
4                        False  

[5 rows x 61 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
le.fit( data['income'] )

LabelEncoder()

In [10]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [11]:
# example of transforming dataset of income values

le.transform( [ '<=50K', '>50K', '>50K' ] )

array([0, 1, 1])

In [12]:
# transform income column with existing dataset

y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int64

In [16]:
model = LogisticRegression(max_iter=1000)

In [17]:
X

age  educational-num  gender_Female  gender_Male  native-country_?  \
0       25                7          False         True             False   
1       38                9          False         True             False   
2       28               12          False         True             False   
3       44               10          False         True             False   
4       18               10           True        False             False   
...    ...              ...            ...          ...               ...   
48837   27               12           True        False             False   
48838   40                9          False         True             False   
48839   58                9           True        False             False   
48840   22                9          False         True             False   
48841   52                9           True        False             False   

       native-country_Cambodia  native-country_Canada  native-country_China  \
0                        False                  False                 False   
1                        False                  False                 False   
2                        False                  False                 False   
3                        False                  False                 False   
4                        False                  False                 False   
...                        ...                    ...                   ...   
48837                    False                  False                 False   
48838                    False                  False                 False   
48839                    False                  False                 False   
48840                    False                  False                 False   
48841                    False                  False                 False   

       native-country_Columbia  native-country_Cuba  ...  \
0                        False                False  ...   
1                        False                False  ...   
2                        False                False  ...   
3                        False                False  ...   
4                        False                False  ...   
...                        ...                  ...  ...   
48837                    False                False  ...   
48838                    False                False  ...   
48839                    False                False  ...   
48840                    False                False  ...   
48841                    False                False  ...   

       occupation_Farming-fishing  occupation_Handlers-cleaners  \
0                           False                         False   
1                            True                         False   
2                           False                         False   
3                           False                         False   
4                           False                         False   
...                           ...                           ...   
48837                       False                         False   
48838                       False                         False   
48839                       False                         False   
48840                       False                         False   
48841                       False                         False   

       occupation_Machine-op-inspct  occupation_Other-service  \
0                              True                     False   
1                             False                     False   
2                             False                     False   
3                              True                     False   
4                             False                     False   
...                             ...                       ...   
48837                         False                     False   
48838                          True                     False   
48839                 

In [18]:
# machine learning

model.fit( X, y )
predictions = model.predict_proba( X )

In [19]:
predictions[:5]

array([[0.94519806, 0.05480194],
       [0.91085435, 0.08914565],
       [0.66412322, 0.33587678],
       [0.77188099, 0.22811901],
       [0.98719759, 0.01280241]])

In [20]:
# fact & prediction check
# @todo: check diff b/w real and testing collection

zip( predictions[:, 1], y )

In [21]:
model.predict(X)

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
model.score(X, y)

0.8053314770074935